### ISSUE TITLE
Cant add an Gameserver Ip Adress over 11 characters

### ISSUE THREAD

**Issue by darkysmile1** [riffy/gta-adminlte-django#7]
Hy,

i cant add an ip adress over 11 Characters, my Adress has 14 characters.

**Comment by riffy** [comment]
Thanks for the issue. 

For now you can make the following changes:
1. Go into `adminlte/models.py` and change the ip attribute from `ip = models.CharField(max_length=11, help_text="IP of the gameserver. Can be localhost.", default="")` to `ip = models.CharField(max_length=14, help_text="IP of the gameserver. Can be localhost.", default="")` (changing the max_length parameter)
2. Run `python .\manage.py makemigrations`
3. Run `python .\manage.py migrate --run-syncdb`

I will fix this with an upcoming update, considering also IPv6 as ip addresses :)
